### ISSUE TITLE
Can't change profile pictures!

### ISSUE THREAD

**Issue by ImminentDoom** [FYCompsci/TwitHalf#4]
I'd love it if we could change our profile picture! Thanks @malsf21 , I love your site so far!

**Comment by mattxwang** [comment]
Thanks for giving us this feedback @ImminentDoom , but I don't think we'll be implementing this feature anytime soon. Coupled with information storage issues and consistent profile pictures, we'll keep them as is for now. Maybe in the future if our design philosophy changes, but definitely not for now.

Thanks for the feedback, and I hope you keep on enjoying The Buzz!
